export const BOOK_CREATE_REQUEST ="BOOK_CREATE_REQUEST";
export const BOOK_CREATE_SUCCESS ="BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAIL = "BOOK_CREATE_FAIL";


export const BOOK_GET_REQUEST = "BOOK_GET_REQUEST"
export const BOOK_GET_SUCCESS = "BOOK_GET_SUCCESS"
export const BOOK_GET_FAIL = "BOOK_GET_FAIL"

export const BOOK_UPDATE_REQUEST = "BOOK_UPDATE_REQUEST"
export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS"
export const BOOK_UPDATE_FAIL = " BOOK_UPDATE_FAIL"

export const BOOK_DELETE_REQUEST= "BOOK_DELETE_REQUEST"
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS"
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL"